version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    labels:
      - dependencies

  # Copy of above config for formplayer
  - package-ecosystem: gradle
    directory: "/"
    target-branch: "formplayer"
    schedule:
      interval: daily
    labels:
      - dependencies
